.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH CORRUPT 1
.SH NAME
\fRcorrupt \- modify files by randomly changing bits\fP
.PP
.SH SYNOPSIS
\fBcorrupt\fR [\fB\-n\fR \fIBITS\fR]\fP
.PP
.SH DESCRIPTION
\fBcorrupt\fR modifies files by toggling a randomly chosen bit.\fP
.PP
.SH OPTIONS
.TP
\fB\-n\fR=\fIBITS\fP
.PP
\fRSet the number of bits to modify\fP
.PP
