.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SIMPLE 1
.SH DESCRIPTION
\fRPass \fP\f(CB\-\-help\fP\fR for info.\fP
.PP
.SH OPTIONS
.TP
\f(CB\-v\fP\f(CR \fP\f(CB\-\-verbose\fP
\fRUse verbose output\fP
.PP
.TP
\f(CB\-\-help\fP
\fRPrint usage\fP
.PP
.TP
\f(CB\-\-version\fP
\fRPrint version\fP
.PP
\fRProgram exits when done.\fP
.PP
