.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SIMPLE 1
.SH DESCRIPTION
.PP
\fRPass \fP\f(CB\-\-help\fP\fR for info.\fP
.SH OPTIONS
.TP
\f(CB\-v\fP\f(CR \fP\f(CB\-\-verbose\fP
\fRUse verbose output\fP
.PP
.TP
\f(CB\-\-help\fP
\fRPrint usage\fP
.PP
.TP
\f(CB\-\-version\fP
\fRPrint version\fP
.PP
\fR* \fP\fRbanana\fP
.PP
\fR* \fP\fR.second banana\fP
.PP
\fR* \fP\fRapple\fP
.PP
\fR* \fP\fRdurian\fP
.PP
\fR1. \fP\fRbanana\fP
.PP
\fR2. \fP\fR.second banana\fP
.PP
\fR3. \fP\fRapple\fP
.PP
\fR4. \fP\fRdurian\fP
.PP
.PP
.nf
\fRExit code:
 0: if OK
 1: if not OK\fP
.fi
.PP
\fRA few lines of text .can  be   here\fP