.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SIMPLE 1
.SH DESCRIPTION
.PP
\fRPass \fP\fB\-\-help\fP\fR for info.\fP
.SH OPTIONS
.TP
\fB\-v\fP\f(CR \fP\fB\-\-verbose\fP
\fRUse verbose output\fP
.PP
.TP
\fB\-\-help\fP
\fRPrint usage\fP
.PP
.TP
\fB\-\-version\fP
\fRPrint version\fP
.PP
.nf
\fRExit code:
 0: if OK
 1: if not OK\fP
.fi
.PP
\fRA few lines of text .can  be   here\fP